FTBFS fix for Hurd
Use "__APPLE__" instead of "__MACH__" if the code is only for macOS.

----
i686-gnu-gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc/lib/ppmd -Isrc/lib/buffer -I/usr/include/python3.11 -c src/lib/buffer/ThreadDecoder.c -o build/temp.hurd-i686-cpython-311/src/lib/buffer/ThreadDecoder.o
src/lib/buffer/ThreadDecoder.c:8:10: fatal error: mach/clock.h: No such file or directory
    8 | #include <mach/clock.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/i686-gnu-gcc' failed with exit code 1